Repository chinapandaman/PyPDFForm, pull requests merged in 2024-10, with the labels that each got.

#746 PPF-745: update Python 3.13
  .github/workflows/python-package.yml
  setup.py
Labels: documentation, enhancement

#748 PPF-747: update developer guide on lengthy PRs
  docs/dev_changes.md
Labels: documentation

#750 PPF-750: Improve Integer and Float Input Handling in PdfWrapper.fill() Method
  PyPDFForm/wrapper.py
  pdf_samples/sample_filled_boolean_and_ints.pdf
  pdf_samples/sample_filled_large_and_small_ints.pdf
  pdf_samples/sample_filled_negative_and_positive_floats_and_int.pdf
  pdf_samples/sample_filled_varied_float_values.pdf
  pdf_samples/sample_filled_varied_ints.pdf
  pdf_samples/sample_filled_with_empty_string_and_int.pdf
  tests/test_fill_method.py
Labels: enhancement

#752 PPF-751: cleanup PR-750
  PyPDFForm/middleware/base.py
  PyPDFForm/middleware/text.py
  PyPDFForm/wrapper.py
  tests/test_fill_method.py
Labels: enhancement

#754 PPF-753: cleanup PR-750 test resources
  pdf_samples/fill_method/sample_filled_boolean_and_ints.pdf
  pdf_samples/fill_method/sample_filled_large_and_small_ints.pdf
  pdf_samples/fill_method/sample_filled_negative_and_positive_floats_and_int.pdf
  pdf_samples/fill_method/sample_filled_varied_float_values.pdf
  pdf_samples/fill_method/sample_filled_varied_ints.pdf
  pdf_samples/fill_method/sample_filled_with_empty_string_and_int.pdf
  tests/test_fill_method.py
Labels: enhancement
